version: '2'
services:
  collectd:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile.collectd
    environment:
      SF_API_TOKEN: testing
      SF_INGEST_HOST: fake_sfx
    depends_on:
      - fake_sfx
      - solr6


  solr6:
    image: solr:6.6
    ports:
      - "8983:8983"
    command:
      - -f
      - -e
      - cloud
      - -cloud
      - -noprompt

  fake_sfx:
    build:
      context: .
      dockerfile: Dockerfile.sink

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - collectd
