version: '2'
services:
  collectd:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile.collectd
    environment:
      SF_API_TOKEN: testing
      SF_INGEST_HOST: fake_sfx
    depends_on:
      - fake_sfx
      - solr101


  collectdamazon2017:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile.collectd.amazon2017.03
    depends_on:
      - fake_sfx
      - solr101

  solr101:
    image: solr:6.6
    ports:
      - "8983:8983"
    command: /opt/solr/bin/solr -e cloud -noprompt

  fake_sfx:
    build:
      context: .
      dockerfile: Dockerfile.sink

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - collectd

  test26: # this is to test that python2.6 works (because collectd is linked to 2.6 on amazon)
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - collectdamazon2017
